### PR TITLE
fix: add 'generic' app to INSTALLED_APPS

### PR DESCRIPTION
**Pull request by koeaw**
Include new app introduced in apis-core-rdf v0.10.0 release

### CODE REVIEW

**Comment by b1rger** [comment]
thanks! could you make this a `fix:`?

**Comment by koeaw** [comment]
> thanks! could you make this a `fix:`?

Sure! Also hum, didn't see that formatting changes got included as well, do you mind them?

**Comment by b1rger** [comment]
> Also hum, didn't see that formatting changes got included as well, do you mind them?

ah, I haven't looked at the changes. yeah, please remove them, but feel free to open a separate PR for fixing the formatting

**Comment by koeaw** [comment]
Sure, will remove them. I think they only got applied because I temp. added the repo as "sibling" to the others in my IDE, which made it reuse the linting rules for `apis-core-rdf`.

**Comment by b1rger** [comment]
Thanks!

**Pull request merged**
